### ISSUE TITLE
Provide a meaningful NServiceBus hostname

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureFunctions#42]
For Service Pulse, the hostname for the endpoints running in Azure Functions should be more meaningful than a random machine name.

One option is to set hostname to the Azure Function App (App Service) name available from the [environment variable](https://docs.microsoft.com/en-ca/azure/azure-functions/functions-dotnet-class-library#environment-variables).

```c#
System.Environment.GetEnvironmentVariable("WEBSITE_SITE_NAME", 
  EnvironmentVariableTarget.Process);
```

**Comment by timbussmann** [comment]
@SeanFeldman so that's a variable not being set when running locally?

**Comment by SeanFeldman** [comment]
Correct.

**Comment by timbussmann** [comment]
what would be the difference if we would put the value to the endpoint name instead?
Would it be valuable to be somehow able to differentiate between different function "instances" (e.g. to find out about caching issues)? Is there a unique identifier per function instance?

**Comment by SeanFeldman** [comment]
`WEBSITE_SITE_NAME` represents an Azure Function App, not a single Function. When scaling out, it's the Function App that is scaling, not a single Function/NServiceBus Endpoint. Also, A Function can host multiple NServiceBus endpoints. And if an endpoint name is used, it will misrepresent what's scaled out. That's why we thought Function App name would be more suitable.
